resourceType: "Bundle"
identifier<Identifier>$(Persistent identifier for the bundle$):
type<code=document|message|transaction|transaction-response|batch|batch-response|history|searchset>$(R!  document | message | transaction | transaction-response | batch | batch-response | history | searchset | collection$):
total<unsignedInt>$(C? If search, the total number of matches$):
link<list>$(Links related to this Bundle$):
  - relation<string>$(R!  See http://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-1$):
    url<uri>$(R!  Reference details for the link$):
entry<list>$(Entry in the bundle - will have a resource or information$):
  - link<list::Content as for Bundle.link>$(Links related to this entry$):
    fullUrl<uri>$(Absolute URL for resource (server address, or UUID/OID)$):
    resource<Resource>$(A resource in the bundle$):
    search:
        mode<code>$(match | include | outcome - why this is in the result set$):
        score<decimal>$(Search ranking (between 0 and 1)$):
    request:
        method<code=GET|POST|PUT>$(R!  GET | POST | PUT | DELETE$):
        url<uri>$(R!  URL for HTTP equivalent of this entry$):
        ifNoneMatch<string>$(For managing cache currency$):
        ifModifiedSince<instant>$(For managing update contention$):
        ifMatch<string>$(For managing update contention$):
        ifNoneExist<string>$(For conditional creates$):
    response:
        status<string>$(R!  Status response code (text optional)$):
        location<uri>$(The location, if the operation returns a location$):
        etag<string>$(The etag for the resource (if relevant)$):
        lastModified<instant>$(Server's date time modified$):
        outcome<Resource>$(OperationOutcome with hints and warnings (for batch/transaction)$):
signature<Signature>$(Digital Signature$):