resourceType: "List"
identifier<list::Identifier>$(Business identifier$):
status<code=current|retired>$(R!  current | retired | entered-in-error$):
mode<code=working|snapshot>$(R!  working | snapshot | changes$):
title<string>$(Descriptive name for the list$):
code<CodeableConcept>$(What the purpose of this list is$):
subject<Reference(Patient|Group|Device|Location)>$(If all resources have the same subject$):
encounter<Reference(Encounter)>$(Context in which list created$):
date<dateTime>$(When the list was prepared$):
source<Reference(Practitioner|Patient|Device)>$(Who and/or what defined the list contents (aka Author)$):
orderedBy<CodeableConcept>$(What order the list has$):
note<list::Annotation>$(Comments about the list$):
entry<list>$(C? Entries in the list$):
  - flag<CodeableConcept>$(Status/Workflow information about this item$):
    deleted<boolean>$(C? If this item is actually marked as deleted$):
    date<dateTime>$(When item added to list$):
    item<Reference(Any)>$(R!  Actual entry$):
emptyReason<CodeableConcept>$(C? Why list is empty$):